version: '2'

services:
  # backend service for all apps
  backend:
    build: ./prototype-backend/
    ports:
      - "8080:8080"
    volumes:
      - ./prototype-backend:/home/app
      - /home/app/node_modules
    environment:
      - PORT=8080

  # main roca app
  las_roca:
    build: ./lvm-las-roca/
    ports:
      - "3000:3000"
    volumes:
      - ./lvm-las-roca:/home/app
      - /home/app/node_modules
      - /home/app/public
    environment:
      - PORT=3000
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://localhost:3001
      - LETTER_URL=http://localhost:3002
      - DAMAGE_URL=http://localhost:3003

  # postbox app (sprinc mvc based)
  las_postbox:
    build: ./lvm-las-postbox/
    ports:
      - "3001:3001"
    volumes:
      - ./lvm-las-postbox:/home/app
      - /home/app/node_modules
      - /home/app/src/main/resources/static
    environment:
      - SERVER_PORT=3001
      # - LAS_REST_SERVICE_URL=http://backend:8080
      - lasRestServiceUrl=http://backend:8080
      - lasRocaUrl=http://localhost:3000

  # letter generation app
  las_letter:
    build: ./lvm-las-letter/
    ports:
      - "3002:3002"
    volumes:
      - ./lvm-las-letter:/home/app
      - /home/app/node_modules
      - /home/app/public
    environment:
      - PORT=3002
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://localhost:3001
      - ROCA_URL=http://localhost:3000

  # damage report app
  las_damage:
    build: ./lvm-las-damage/
    ports:
      - "3003:3003"
    volumes:
      - ./lvm-las-damage:/home/app
      - /home/app/node_modules
      - /home/app/public
    environment:
      - PORT=3003
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - POSTBOX_URL=http://localhost:3001
      - ROCA_URL=http://localhost:3000
